title: Ehsanul Bashar Pranto
description: My Data Science Portfolio
baseurl: "" # Keep this empty
url: "https://ebpranto.github.io" # Change to your GitHub Pages link
theme: jekyll_theme_minimal

author:
  name: Ehsanul Bashar Pranto
  email: ehsanulbashar190@gmail.com

# # Navigation Bar
# header_pages:
#   - index.md
#   - projects.md
#   - contact.md

# Optional: Social
linkedin_username: your-linkedin-username
github_username: your-github-username
